import { BusStop, TrafficIncident } from './types';

/**
 * ALL INVENTED APPLICATION DATA
 * Contained in this single file as requested.
 * Contains at least 5 rows of traffic incidents and 6 bus stops with live arrival info.
 */

export const TRAFFIC_INCIDENTS_DATA: TrafficIncident[] = [
  {
    id: 'inc-001',
    location: 'Central Expressway (CTE) towards City near Moulmein Exit',
    type: 'Heavy Traffic',
    impactDescription: 'Heavy congestion stretching 1.8km. Expect additional 12-15 min travel time.',
    affectedBuses: ['65', '147', '857'],
    delayMinutes: 14,
    reportedTimeAgo: '4 mins ago',
    advice: 'Commuters traveling towards Dhoby Ghaut / CBD are advised to take the North-East Line (NE8 Farrer Park) or North-South Line (NS20 Novena) to avoid CTE congestion.',
    lanesAffected: 'All city-bound lanes moving at ~15 km/h',
    estimatedClearance: '~25 mins (peak easing)',
    source: 'LTA EMAS / Expressway Monitoring & Advisory System',
  },
  {
    id: 'inc-002',
    location: 'Orchard Boulevard junction with Paterson Road',
    type: 'Accident',
    impactDescription: 'Left two lanes blocked due to multi-vehicle collision. Traffic slow moving.',
    affectedBuses: ['14', '106', '111'],
    delayMinutes: 20,
    reportedTimeAgo: '8 mins ago',
    advice: 'Traffic police and EMAS recovery tow trucks on site. Motorists and bus commuters should expect slow progress between Grange Road and Paterson Hill.',
    lanesAffected: 'Lanes 1 & 2 (Leftmost)',
    estimatedClearance: '~35 mins (towing in progress)',
    source: 'Traffic Police & LTA EMAS',
  },
  {
    id: 'inc-003',
    location: 'Victoria Street near Middle Road intersection',
    type: 'Road Works',
    impactDescription: 'Scheduled underground cabling repair. Lane 3 closed until 18:00.',
    affectedBuses: ['2', '12', '33', '133'],
    delayMinutes: 8,
    reportedTimeAgo: '15 mins ago',
    advice: 'Buses turning onto Middle Road may experience minor queuing. Consider walking to Bugis MRT (EW12/DT14) for fast transfers.',
    lanesAffected: 'Lane 3 (Kerbside bus lane diverted)',
    estimatedClearance: 'Until 18:00 SGT',
    source: 'SP Group & LTA Road Operations',
  },
  {
    id: 'inc-004',
    location: 'Somerset Road outside Youth Park',
    type: 'Vehicle Breakdown',
    impactDescription: 'Broken-down goods vehicle blocking lane 1. Clearance operation underway.',
    affectedBuses: ['143', '167', '190'],
    delayMinutes: 11,
    reportedTimeAgo: '19 mins ago',
    advice: 'Single-lane constriction before Penang Road turnoff. Commuters heading towards Clarke Quay can take NS23 Somerset MRT.',
    lanesAffected: 'Lane 1 (Rightmost turn pocket)',
    estimatedClearance: '~15 mins',
    source: 'LTA EMAS Patrol',
  },
  {
    id: 'inc-005',
    location: 'Bras Basah Road before Raffles Boulevard',
    type: 'Lane Closure',
    impactDescription: 'Temporary water main inspection. Speed reduction enforced to 40km/h.',
    affectedBuses: ['7', '77', '174'],
    delayMinutes: 6,
    reportedTimeAgo: '27 mins ago',
    advice: 'PUB inspection team on location with directional arrow boards. Minor deceleration expected.',
    lanesAffected: 'Lane 4 (Left lane)',
    estimatedClearance: '~40 mins',
    source: 'PUB & LTA Operations',
  },
  {
    id: 'inc-006',
    location: 'Nicoll Highway towards Marina Bay',
    type: 'Heavy Traffic',
    impactDescription: 'Peak hour surge along arterial corridor. Bottleneck approaching flyover.',
    affectedBuses: ['10', '70', '196'],
    delayMinutes: 9,
    reportedTimeAgo: '32 mins ago',
    advice: 'Volume heavy after Suntec City entrance. Commuters can transfer to CC4 Promenade MRT to bypass highway delays.',
    lanesAffected: 'General bottleneck along southbound carriageway',
    estimatedClearance: '~30 mins',
    source: 'LTA Traffic Control Centre',
  },
];

export const BUS_STOPS_DATA: BusStop[] = [
  {
    id: 'stop-09048',
    code: '09048',
    name: 'Opp Orchard Boulevard Stn',
    road: 'Orchard Blvd',
    distanceMeters: 65,
    walkingTimeMins: 1,
    busServices: ['14', '65', '106', '111', '174'],
    buses: [
      {
        busNumber: '14',
        destination: 'Bedok Bus Interchange',
        isDelayed: true,
        delayReason: 'Paterson Rd Accident',
        delayMinutes: 18,
        nextBus: {
          arrivalMinutes: 16,
          load: 'Standing Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 28,
          load: 'Seats Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 38,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '65',
        destination: 'Tampines Central Interchange',
        isDelayed: true,
        delayReason: 'CTE Heavy Congestion',
        delayMinutes: 12,
        nextBus: {
          arrivalMinutes: 11,
          load: 'Limited Standing',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 22,
          load: 'Standing Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 34,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '106',
        destination: 'Shenton Way Bus Terminal',
        isDelayed: true,
        delayReason: 'Paterson Rd Collision',
        delayMinutes: 15,
        nextBus: {
          arrivalMinutes: 9,
          load: 'Standing Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 19,
          load: 'Seats Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 29,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
      {
        busNumber: '111',
        destination: 'Ghim Moh Bus Terminal',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 2,
          load: 'Seats Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 13,
          load: 'Seats Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 24,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '174',
        destination: 'New Bridge Road Terminal',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 5,
          load: 'Seats Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 16,
          load: 'Standing Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 27,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
    ],
  },
  {
    id: 'stop-08057',
    code: '08057',
    name: 'Somerset Station Gate B',
    road: 'Somerset Rd',
    distanceMeters: 140,
    walkingTimeMins: 2,
    busServices: ['7', '143', '167', '190', '972'],
    buses: [
      {
        busNumber: '7',
        destination: 'Bedok Interchange via Bugis',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 1,
          load: 'Seats Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 9,
          load: 'Standing Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 19,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
      {
        busNumber: '143',
        destination: 'Jurong East Bus Interchange',
        isDelayed: true,
        delayReason: 'Somerset Rd Vehicle Breakdown',
        delayMinutes: 10,
        nextBus: {
          arrivalMinutes: 13,
          load: 'Limited Standing',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 24,
          load: 'Standing Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 35,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
      {
        busNumber: '167',
        destination: 'Bukit Merah Interchange',
        isDelayed: true,
        delayReason: 'Somerset Rd Obstruction',
        delayMinutes: 8,
        nextBus: {
          arrivalMinutes: 7,
          load: 'Standing Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 18,
          load: 'Seats Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 30,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '190',
        destination: 'Choa Chu Kang Interchange',
        isDelayed: true,
        delayReason: 'Youth Park Obstruction',
        delayMinutes: 11,
        nextBus: {
          arrivalMinutes: 14,
          load: 'Standing Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 21,
          load: 'Seats Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 31,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
      {
        busNumber: '972',
        destination: 'Bukit Panjang Interchange',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 4,
          load: 'Seats Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 12,
          load: 'Seats Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 22,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
    ],
  },
  {
    id: 'stop-08031',
    code: '08031',
    name: 'Dhoby Ghaut Station Plaza',
    road: 'Orchard Rd',
    distanceMeters: 290,
    walkingTimeMins: 4,
    busServices: ['16', '36', '77', '124', '174'],
    buses: [
      {
        busNumber: '16',
        destination: 'Bedok Interchange via Marine Parade',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 3,
          load: 'Seats Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 12,
          load: 'Standing Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 25,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '36',
        destination: 'Changi Airport Terminal 2',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 6,
          load: 'Seats Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 14,
          load: 'Standing Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 22,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '77',
        destination: 'Marina Centre Terminal',
        isDelayed: true,
        delayReason: 'Bras Basah Lane Closure',
        delayMinutes: 7,
        nextBus: {
          arrivalMinutes: 8,
          load: 'Standing Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 20,
          load: 'Seats Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 32,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '124',
        destination: 'Telok Blangah Drive Loop',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 0, // Arrived
          load: 'Seats Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 11,
          load: 'Seats Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 23,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '174',
        destination: 'Boon Lay Interchange',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 8,
          load: 'Seats Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 17,
          load: 'Standing Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 29,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
    ],
  },
  {
    id: 'stop-01012',
    code: '01012',
    name: 'Bugis Junction North',
    road: 'Victoria St',
    distanceMeters: 450,
    walkingTimeMins: 6,
    busServices: ['2', '12', '33', '130', '133'],
    buses: [
      {
        busNumber: '2',
        destination: 'Changi Village Terminal',
        isDelayed: true,
        delayReason: 'Victoria St Road Works',
        delayMinutes: 8,
        nextBus: {
          arrivalMinutes: 10,
          load: 'Limited Standing',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 19,
          load: 'Standing Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 30,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '12',
        destination: 'Pasir Ris Bus Interchange',
        isDelayed: true,
        delayReason: 'Victoria St Lane Closure',
        delayMinutes: 9,
        nextBus: {
          arrivalMinutes: 7,
          load: 'Standing Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 16,
          load: 'Standing Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 28,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
      {
        busNumber: '33',
        destination: 'Kent Ridge Bus Terminal',
        isDelayed: true,
        delayReason: 'Underground Cable Repairs',
        delayMinutes: 6,
        nextBus: {
          arrivalMinutes: 5,
          load: 'Seats Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 17,
          load: 'Standing Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 29,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '130',
        destination: 'Ang Mo Kio Interchange',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 2,
          load: 'Seats Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 12,
          load: 'Seats Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 21,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '133',
        destination: 'Shenton Way Bus Terminal',
        isDelayed: true,
        delayReason: 'Victoria St Road Works',
        delayMinutes: 8,
        nextBus: {
          arrivalMinutes: 11,
          load: 'Standing Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 22,
          load: 'Seats Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 34,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
    ],
  },
  {
    id: 'stop-04121',
    code: '04121',
    name: 'Opp City Hall Complex',
    road: 'North Bridge Rd',
    distanceMeters: 620,
    walkingTimeMins: 8,
    busServices: ['32', '51', '61', '63', '80'],
    buses: [
      {
        busNumber: '32',
        destination: 'Bedok Interchange via Kallang',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 0, // Arr
          load: 'Seats Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 10,
          load: 'Standing Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 22,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '51',
        destination: 'Jurong East Bus Interchange',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 4,
          load: 'Standing Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 14,
          load: 'Seats Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 25,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
      {
        busNumber: '61',
        destination: 'Bukit Batok Bus Interchange',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 9,
          load: 'Seats Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 19,
          load: 'Seats Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 31,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '63',
        destination: 'Eunos Interchange via Chinatown',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 1,
          load: 'Seats Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 11,
          load: 'Standing Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 23,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '80',
        destination: 'Sengkang Bus Interchange',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 7,
          load: 'Standing Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 16,
          load: 'Seats Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 27,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
    ],
  },
  {
    id: 'stop-03019',
    code: '03019',
    name: 'Raffles Place Promenade',
    road: 'Collyer Quay',
    distanceMeters: 850,
    walkingTimeMins: 11,
    busServices: ['10', '70', '100', '107', '196'],
    buses: [
      {
        busNumber: '10',
        destination: 'Tampines Interchange via East Coast',
        isDelayed: true,
        delayReason: 'Nicoll Highway Congestion',
        delayMinutes: 9,
        nextBus: {
          arrivalMinutes: 12,
          load: 'Limited Standing',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 23,
          load: 'Standing Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 34,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
      {
        busNumber: '70',
        destination: 'Yio Chu Kang Interchange',
        isDelayed: true,
        delayReason: 'Marina Bay Surge',
        delayMinutes: 7,
        nextBus: {
          arrivalMinutes: 6,
          load: 'Standing Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 17,
          load: 'Seats Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 28,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
      {
        busNumber: '100',
        destination: 'Ghim Moh Bus Terminal',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 3,
          load: 'Seats Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 14,
          load: 'Seats Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 25,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '107',
        destination: 'Hougang Central Interchange',
        isDelayed: false,
        nextBus: {
          arrivalMinutes: 5,
          load: 'Seats Available',
          type: 'Single Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 16,
          load: 'Standing Available',
          type: 'Single Deck',
        },
        thirdBus: {
          arrivalMinutes: 28,
          load: 'Seats Available',
          type: 'Single Deck',
        },
      },
      {
        busNumber: '196',
        destination: 'Clementi Interchange',
        isDelayed: true,
        delayReason: 'Nicoll Highway Bottleneck',
        delayMinutes: 9,
        nextBus: {
          arrivalMinutes: 15,
          load: 'Standing Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        },
        subsequentBus: {
          arrivalMinutes: 26,
          load: 'Seats Available',
          type: 'Double Deck',
        },
        thirdBus: {
          arrivalMinutes: 37,
          load: 'Seats Available',
          type: 'Double Deck',
        },
      },
    ],
  },
];
