import { BusStop, TrafficIncident } from './types';

/**
 * ALL INVENTED APPLICATION DATA
 * Kept in this single file with over 40 bus stop rows and traffic incidents.
 * Single source of truth across all three screens.
 */

export const TRAFFIC_INCIDENTS_DATA: TrafficIncident[] = [
  {
    id: 'inc-001',
    location: 'Central Expressway (CTE) towards City near Moulmein Exit',
    type: 'Heavy Traffic',
    impactDescription: 'Heavy congestion stretching 1.8km. Expect additional 12-15 min travel time.',
    affectedBuses: ['65', '147', '857'],
    delayMinutes: 14,
    issuedTime: '08:14 SGT',
    reportedTimeAgo: '6 mins ago',
    advice: 'Commuters traveling towards Dhoby Ghaut / CBD are advised to take the North-East Line or North-South Line to avoid CTE congestion.',
    lanesAffected: 'All city-bound lanes moving at ~15 km/h',
    estimatedClearance: '~25 mins (peak easing)',
    source: 'LTA EMAS / Expressway Monitoring & Advisory System',
    isExampleData: true,
  },
  {
    id: 'inc-002',
    location: 'Orchard Boulevard junction with Paterson Road',
    type: 'Accident',
    impactDescription: 'Left two lanes blocked due to multi-vehicle collision. Traffic slow moving.',
    affectedBuses: ['14', '106', '111'],
    delayMinutes: 20,
    issuedTime: '08:10 SGT',
    reportedTimeAgo: '10 mins ago',
    advice: 'Traffic police and EMAS recovery tow trucks on site. Motorists and bus commuters should expect slow progress between Grange Road and Paterson Hill.',
    lanesAffected: 'Lanes 1 & 2 (Leftmost)',
    estimatedClearance: '~30 mins (towing in progress)',
    source: 'Traffic Police & LTA EMAS',
    isExampleData: true,
  },
  {
    id: 'inc-003',
    location: 'Victoria Street near Middle Road intersection',
    type: 'Road Works',
    impactDescription: 'Scheduled underground cabling repair. Lane 3 closed until 18:00.',
    affectedBuses: ['2', '12', '33', '133'],
    delayMinutes: 8,
    issuedTime: '08:02 SGT',
    reportedTimeAgo: '18 mins ago',
    advice: 'Buses turning onto Middle Road may experience minor queuing. Consider walking to Bugis MRT for fast transfers.',
    lanesAffected: 'Lane 3 (Kerbside bus lane diverted)',
    estimatedClearance: 'Until 18:00 SGT',
    source: 'SP Group & LTA Road Operations',
    isExampleData: true,
  },
  {
    id: 'inc-004',
    location: 'Upper Thomson Road outside Thomson Plaza',
    type: 'Vehicle Breakdown',
    impactDescription: 'Broken-down delivery lorry blocking bus bay entrance. Queuing onto main road.',
    affectedBuses: ['52', '132', '162', '165', '166', '410G', '410W'],
    delayMinutes: 12,
    issuedTime: '08:08 SGT',
    reportedTimeAgo: '12 mins ago',
    advice: 'Buses are boarding passengers from the adjacent lane. Expect moderate boarding delays at stops 50161 and 50169.',
    lanesAffected: 'Bus bay approach lane',
    estimatedClearance: '~20 mins (tow truck en route)',
    source: 'LTA Operations',
    isExampleData: true,
  },
  {
    id: 'inc-005',
    location: 'Somerset Road outside Youth Park',
    type: 'Vehicle Breakdown',
    impactDescription: 'Broken-down goods vehicle blocking lane 1. Clearance operation underway.',
    affectedBuses: ['143', '167', '190'],
    delayMinutes: 11,
    issuedTime: '07:55 SGT',
    reportedTimeAgo: '25 mins ago',
    advice: 'Single-lane constriction before Penang Road turnoff. Commuters heading towards Clarke Quay can take NS23 Somerset MRT.',
    lanesAffected: 'Lane 1 (Rightmost turn pocket)',
    estimatedClearance: '~15 mins',
    source: 'LTA EMAS Patrol',
    isExampleData: true,
  },
  {
    id: 'inc-006',
    location: 'Bras Basah Road before Raffles Boulevard',
    type: 'Lane Closure',
    impactDescription: 'Temporary water main inspection. Speed reduction enforced to 40km/h.',
    affectedBuses: ['7', '77', '174'],
    delayMinutes: 6,
    issuedTime: '07:45 SGT',
    reportedTimeAgo: '35 mins ago',
    advice: 'PUB inspection team on location with directional arrow boards. Minor deceleration expected.',
    lanesAffected: 'Lane 4 (Left lane)',
    estimatedClearance: '~40 mins',
    source: 'PUB & LTA Operations',
    isExampleData: true,
  },
];

// Helper to generate realistic arrivals adhering to requirement (g):
// "Where a third arrival does not exist, the screen says in words why — no more buses tonight, or only two are known — instead of 'N/A'."
function generateArrivals(
  busNumber: string,
  destination: string,
  baseArr1: number,
  baseArr2: number,
  hasThird: boolean,
  thirdReason?: string
): import('./types').BusArrivalInfo {
  const isDelayed = ['14', '106', '111', '65', '147', '52', '165', '166', '410G'].includes(busNumber);
  const delayMinutes = isDelayed ? 8 : 0;
  const arr1 = Math.max(0, baseArr1);
  const arr2 = arr1 + Math.max(5, baseArr2);
  const arr3 = arr2 + 9;

  const nextLoad: 'Seats Available' | 'Standing Available' | 'Limited Standing' =
    arr1 < 3 ? 'Limited Standing' : 'Seats Available';

  return {
    busNumber,
    destination,
    isDelayed,
    delayMinutes: isDelayed ? delayMinutes : undefined,
    delayReason: isDelayed ? 'Traffic incident reported along service corridor' : undefined,
    nextBus: {
      arrivalMinutes: arr1,
      load: nextLoad,
      type: 'Double Deck',
      wheelchairAccessible: true,
    },
    subsequentBus: {
      arrivalMinutes: arr2,
      load: 'Standing Available',
      type: 'Single Deck',
      wheelchairAccessible: true,
    },
    thirdBus: hasThird
      ? {
          arrivalMinutes: arr3,
          load: 'Seats Available',
          type: 'Double Deck',
          wheelchairAccessible: true,
        }
      : undefined,
    noThirdArrivalReason: hasThird
      ? undefined
      : (thirdReason || 'Only two arrivals scheduled'),
  };
}

export const BUS_STOPS_DATA: BusStop[] = [
  // 1. Stop 09048: Opp Orchard Boulevard Stn (Authoritative service list: 14, 65, 106, 111, 174)
  {
    id: 'stop-09048',
    code: '09048',
    name: 'Opp Orchard Boulevard Stn',
    road: 'Orchard Blvd',
    postalCode: '248649',
    latitude: 1.3023,
    longitude: 103.8242,
    distanceMeters: 65,
    walkingTimeMins: 1,
    busServices: ['14', '65', '106', '111', '174'],
    buses: [
      generateArrivals('14', 'Bedok Int via Clementi / Orchard', 2, 7, true),
      generateArrivals('65', 'Tampines Int via Lower Delta', 4, 8, true),
      generateArrivals('106', 'Shenton Way Ter via Marina Bay', 1, 9, false, 'Only two arrivals scheduled'),
      generateArrivals('111', 'Ghim Moh Ter via Commonwealth', 8, 11, true),
      generateArrivals('174', 'New Bridge Rd Ter via River Valley', 6, 12, false, 'No more buses tonight (last bus in service)'),
    ],
  },

  // 2. Stop 50161: Opp Thomson Plaza (Critical for item a)
  {
    id: 'stop-50161',
    code: '50161',
    name: 'Opp Thomson Plaza',
    road: 'Upp Thomson Rd',
    postalCode: '574408',
    latitude: 1.3547,
    longitude: 103.8315,
    distanceMeters: 120,
    walkingTimeMins: 2,
    busServices: ['52', '132', '162', '163', '165', '166', '167', '410G', '855', '980'],
    buses: [
      generateArrivals('52', 'Jurong East Int via Clementi', 3, 8, true),
      generateArrivals('132', 'Bukit Merah Int via Whitley', 7, 10, true),
      generateArrivals('162', 'Shenton Way Ter via Newton', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('163', 'Toa Payoh Int via Braddell', 5, 9, true),
      generateArrivals('165', 'Clementi Int via Farrer Rd', 2, 7, true),
      generateArrivals('166', 'Clementi Int via Dover Rd', 8, 12, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('167', 'Bukit Merah Int via Orchard', 4, 8, true),
      generateArrivals('410G', 'Bishan Int via Shunfu Rd (Loop)', 0, 6, true),
      generateArrivals('855', 'HarbourFront Int via Queensway', 6, 11, true),
      generateArrivals('980', 'Geylang Lor 1 Ter via Rochor', 9, 14, false, 'Only two arrivals scheduled'),
    ],
  },

  // 3. Stop 50169: Thomson Plaza (Critical for item a)
  {
    id: 'stop-50169',
    code: '50169',
    name: 'Thomson Plaza',
    road: 'Upp Thomson Rd',
    postalCode: '574409',
    latitude: 1.3544,
    longitude: 103.8319,
    distanceMeters: 130,
    walkingTimeMins: 2,
    busServices: ['52', '132', '162', '163', '165', '166', '167', '410W', '855', '980'],
    buses: [
      generateArrivals('52', 'Bishan Int via Sin Ming', 2, 8, true),
      generateArrivals('132', 'Hougang Central Int via Ang Mo Kio', 6, 11, true),
      generateArrivals('162', 'Yio Chu Kang Ter via Upp Thomson', 4, 9, false, 'Only two arrivals scheduled'),
      generateArrivals('163', 'Sengkang Int via Yio Chu Kang', 3, 7, true),
      generateArrivals('165', 'Hougang Central Int via AMK Ave 3', 8, 12, true),
      generateArrivals('166', 'Ang Mo Kio Int via AMK Ave 1', 1, 7, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('167', 'Sembawang Int via Springleaf', 5, 10, true),
      generateArrivals('410W', 'Bishan Int via Marymount (Loop)', 0, 5, true),
      generateArrivals('855', 'Yishun Int via Lentor Ave', 7, 13, true),
      generateArrivals('980', 'Sembawang Int via Gambas Ave', 4, 9, false, 'Only two arrivals scheduled'),
    ],
  },

  // 4. Stop 04121: Opp City Hall Complex
  {
    id: 'stop-04121',
    code: '04121',
    name: 'Opp City Hall Complex',
    road: 'North Bridge Rd',
    postalCode: '179098',
    latitude: 1.2931,
    longitude: 103.8519,
    distanceMeters: 180,
    walkingTimeMins: 2,
    busServices: ['32', '51', '63', '80', '124', '145', '166', '174', '197'],
    buses: [
      generateArrivals('32', 'Bedok Int via Kallang', 2, 8, true),
      generateArrivals('51', 'Hougang Central Int via MacPherson', 5, 11, true),
      generateArrivals('63', 'Eunos Int via Circuit Rd', 1, 7, false, 'Only two arrivals scheduled'),
      generateArrivals('80', 'Sengkang Int via Geylang', 6, 10, true),
      generateArrivals('124', 'St. Michael\'s Ter via Newton', 3, 9, true),
      generateArrivals('145', 'Toa Payoh Int via Balestier', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('166', 'Ang Mo Kio Int via Novena', 4, 9, true),
      generateArrivals('174', 'Kampong Bahru Ter via Clarke Quay', 7, 12, true),
      generateArrivals('197', 'Bedok Int via Guillemard Rd', 0, 6, true),
    ],
  },

  // 5. Stop 04119: City Hall Stn Exit B
  {
    id: 'stop-04119',
    code: '04119',
    name: 'City Hall Stn Exit B',
    road: 'North Bridge Rd',
    postalCode: '179103',
    latitude: 1.2935,
    longitude: 103.8522,
    distanceMeters: 210,
    walkingTimeMins: 3,
    busServices: ['61', '124', '145', '166', '174', '197'],
    buses: [
      generateArrivals('61', 'Eunos Int via MacPherson', 4, 9, true),
      generateArrivals('124', 'St. Michael\'s Ter', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('145', 'Toa Payoh Int', 7, 12, true),
      generateArrivals('166', 'Ang Mo Kio Int', 3, 8, true),
      generateArrivals('174', 'Boon Lay Int', 5, 10, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('197', 'Bedok Int', 2, 7, true),
    ],
  },

  // 6. Stop 09037: Orchard Stn / Lucky Plaza
  {
    id: 'stop-09037',
    code: '09037',
    name: 'Orchard Stn / Lucky Plaza',
    road: 'Orchard Rd',
    postalCode: '238863',
    latitude: 1.3039,
    longitude: 103.8344,
    distanceMeters: 290,
    walkingTimeMins: 4,
    busServices: ['7', '14', '16', '65', '106', '111', '123', '175', '502'],
    buses: [
      generateArrivals('7', 'Bedok Int via Bugis', 1, 6, true),
      generateArrivals('14', 'Bedok Int via Dhoby Ghaut', 3, 8, true),
      generateArrivals('16', 'Bedok Int via Marine Parade', 5, 10, false, 'Only two arrivals scheduled'),
      generateArrivals('65', 'Tampines Int via MacPherson', 2, 7, true),
      generateArrivals('106', 'Shenton Way Ter via Marina Ctr', 6, 11, true),
      generateArrivals('111', 'Ghim Moh Ter', 4, 9, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('123', 'Bukit Merah Int via Havelock', 0, 5, true),
      generateArrivals('175', 'Geylang Lor 1 Ter via Victoria St', 8, 13, true),
      generateArrivals('502', 'Pioneer Rd North via Boon Lay', 7, 12, true),
    ],
  },

  // 7. Stop 08057: Somerset Station Gate B
  {
    id: 'stop-08057',
    code: '08057',
    name: 'Somerset Station Gate B',
    road: 'Somerset Rd',
    postalCode: '238162',
    latitude: 1.3006,
    longitude: 103.8378,
    distanceMeters: 310,
    walkingTimeMins: 4,
    busServices: ['7', '14', '16', '36', '65', '77', '106', '111', '123', '174', '175'],
    buses: [
      generateArrivals('7', 'Bedok Int', 2, 7, true),
      generateArrivals('14', 'Bedok Int', 4, 9, true),
      generateArrivals('16', 'Bedok Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('36', 'Changi Airport PTB2 via Marine Parade', 6, 12, true),
      generateArrivals('65', 'Tampines Int', 3, 8, true),
      generateArrivals('77', 'Marina Ctr Ter via Suntec', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('106', 'Shenton Way Ter', 5, 10, true),
      generateArrivals('111', 'Ghim Moh Ter', 0, 5, true),
      generateArrivals('123', 'HarbourFront Int', 7, 11, true),
      generateArrivals('174', 'New Bridge Rd Ter', 2, 8, true),
      generateArrivals('175', 'Geylang Lor 1 Ter', 9, 14, false, 'Only two arrivals scheduled'),
    ],
  },

  // 8. Stop 08031: Dhoby Ghaut Station Plaza
  {
    id: 'stop-08031',
    code: '08031',
    name: 'Dhoby Ghaut Station Plaza',
    road: 'Orchard Rd',
    postalCode: '238826',
    latitude: 1.2988,
    longitude: 103.8458,
    distanceMeters: 380,
    walkingTimeMins: 5,
    busServices: ['7', '14', '16', '36', '77', '106', '111', '124', '162', '167', '174', '190'],
    buses: [
      generateArrivals('7', 'Bedok Int', 3, 8, true),
      generateArrivals('14', 'Bedok Int', 1, 7, true),
      generateArrivals('16', 'Bedok Int', 6, 11, false, 'Only two arrivals scheduled'),
      generateArrivals('36', 'Changi Airport PTB2', 4, 9, true),
      generateArrivals('77', 'Marina Ctr Ter', 7, 12, true),
      generateArrivals('106', 'Shenton Way Ter', 2, 6, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('111', 'Ghim Moh Ter', 5, 10, true),
      generateArrivals('124', 'St. Michael\'s Ter', 8, 13, true),
      generateArrivals('162', 'Shenton Way Ter', 0, 5, true),
      generateArrivals('167', 'Bukit Merah Int', 9, 14, false, 'Only two arrivals scheduled'),
      generateArrivals('174', 'New Bridge Rd Ter', 3, 8, true),
      generateArrivals('190', 'Kampong Bahru Ter', 1, 6, true),
    ],
  },

  // 9. Stop 01012: Bugis Junction North
  {
    id: 'stop-01012',
    code: '01012',
    name: 'Bugis Junction North',
    road: 'Victoria St',
    postalCode: '188067',
    latitude: 1.3005,
    longitude: 103.856,
    distanceMeters: 420,
    walkingTimeMins: 6,
    busServices: ['2', '12', '33', '130', '133', '960'],
    buses: [
      generateArrivals('2', 'Changi Village Ter via Sims Ave', 2, 7, true),
      generateArrivals('12', 'Pasir Ris Int via Kallang', 5, 10, true),
      generateArrivals('33', 'Bedok Int via Old Airport Rd', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('130', 'Ang Mo Kio Int via Balestier', 7, 12, true),
      generateArrivals('133', 'Ang Mo Kio Int via Serangoon', 3, 8, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('960', 'Woodlands Int via Bukit Panjang', 0, 5, true),
    ],
  },

  // 10. Stop 02049: Suntec City / Promenade Stn
  {
    id: 'stop-02049',
    code: '02049',
    name: 'Suntec City / Promenade Stn',
    road: 'Temasek Blvd',
    postalCode: '038983',
    latitude: 1.2952,
    longitude: 103.8596,
    distanceMeters: 460,
    walkingTimeMins: 6,
    busServices: ['36', '70M', '97', '106', '111', '133', '502', '518'],
    buses: [
      generateArrivals('36', 'Changi Airport PTB2', 4, 9, true),
      generateArrivals('70M', 'Yio Chu Kang Ter', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('97', 'Jurong East Int via AYE', 6, 11, true),
      generateArrivals('106', 'Bukit Batok Int via Commonwealth', 3, 8, true),
      generateArrivals('111', 'Ghim Moh Ter', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('133', 'Shenton Way Ter', 2, 7, true),
      generateArrivals('502', 'Soon Lee Bus Park', 7, 12, true),
      generateArrivals('518', 'Pasir Ris Int via Tampines', 0, 5, true),
    ],
  },

  // 11. Stop 03019: Raffles Place Promenade
  {
    id: 'stop-03019',
    code: '03019',
    name: 'Raffles Place Promenade',
    road: 'Collyer Quay',
    postalCode: '049318',
    latitude: 1.2847,
    longitude: 103.8532,
    distanceMeters: 510,
    walkingTimeMins: 7,
    busServices: ['10', '57', '70', '100', '107', '130', '131', '167', '196'],
    buses: [
      generateArrivals('10', 'Tampines Int via Marine Parade', 3, 8, true),
      generateArrivals('57', 'Bishan Int via Toa Payoh', 5, 10, true),
      generateArrivals('70', 'Yio Chu Kang Ter', 1, 7, false, 'Only two arrivals scheduled'),
      generateArrivals('100', 'Serangoon Int via Geylang', 6, 12, true),
      generateArrivals('107', 'Hougang Central Int', 2, 8, true),
      generateArrivals('130', 'Ang Mo Kio Int', 7, 11, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('131', 'Saint Michael\'s Ter', 4, 9, true),
      generateArrivals('167', 'Sembawang Int', 0, 6, true),
      generateArrivals('196', 'Bedok Int via East Coast Rd', 8, 13, true),
    ],
  },

  // 12. Stop 10169: HarbourFront Stn / VivoCity
  {
    id: 'stop-10169',
    code: '10169',
    name: 'HarbourFront Stn / VivoCity',
    road: 'Telok Blangah Rd',
    postalCode: '099419',
    latitude: 1.2644,
    longitude: 103.8222,
    distanceMeters: 550,
    walkingTimeMins: 8,
    busServices: ['10', '30', '57', '61', '65', '80', '97', '100', '131', '143', '145', '166', '855'],
    buses: [
      generateArrivals('10', 'Tampines Int', 2, 7, true),
      generateArrivals('30', 'Bedok Int via Eunos', 4, 9, true),
      generateArrivals('57', 'Bishan Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('61', 'Eunos Int', 6, 11, true),
      generateArrivals('65', 'Tampines Int', 3, 8, true),
      generateArrivals('80', 'Sengkang Int', 7, 12, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('97', 'Jurong East Int', 5, 10, true),
      generateArrivals('100', 'Serangoon Int', 0, 5, true),
      generateArrivals('131', 'Bukit Merah Int', 8, 13, true),
      generateArrivals('143', 'Toa Payoh Int', 2, 7, true),
      generateArrivals('145', 'Buona Vista Ter', 9, 14, false, 'Only two arrivals scheduled'),
      generateArrivals('166', 'Ang Mo Kio Int', 4, 9, true),
      generateArrivals('855', 'Yishun Int', 1, 6, true),
    ],
  },

  // 13. Stop 10161: Opp HarbourFront Stn
  {
    id: 'stop-10161',
    code: '10161',
    name: 'Opp HarbourFront Stn',
    road: 'Telok Blangah Rd',
    postalCode: '099420',
    latitude: 1.2652,
    longitude: 103.8218,
    distanceMeters: 580,
    walkingTimeMins: 8,
    busServices: ['10', '30', '57', '61', '65', '80', '97', '100', '131', '143', '145', '166', '855'],
    buses: [
      generateArrivals('10', 'Kent Ridge Ter via Pasir Panjang', 3, 8, true),
      generateArrivals('30', 'Boon Lay Int via West Coast', 5, 10, true),
      generateArrivals('57', 'Bukit Merah Int', 1, 7, false, 'Only two arrivals scheduled'),
      generateArrivals('61', 'Bukit Batok Int', 7, 12, true),
      generateArrivals('65', 'HarbourFront Int', 0, 5, true),
      generateArrivals('80', 'HarbourFront Int', 4, 9, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('97', 'Marina Ctr Ter', 2, 8, true),
      generateArrivals('100', 'Ghim Moh Ter', 6, 11, true),
      generateArrivals('131', 'Saint Michael\'s Ter', 8, 13, true),
      generateArrivals('143', 'Jurong East Int', 3, 8, false, 'Only two arrivals scheduled'),
      generateArrivals('145', 'Toa Payoh Int', 9, 14, true),
      generateArrivals('166', 'Clementi Int', 1, 6, true),
      generateArrivals('855', 'HarbourFront Int', 4, 9, true),
    ],
  },

  // 14. Stop 04168: Capitol Bldg
  {
    id: 'stop-04168',
    code: '04168',
    name: 'Capitol Bldg',
    road: 'Stamford Rd',
    postalCode: '178905',
    latitude: 1.2938,
    longitude: 103.8512,
    distanceMeters: 230,
    walkingTimeMins: 3,
    busServices: ['7', '14', '16', '36', '77', '106', '111', '131', '167', '171'],
    buses: [
      generateArrivals('7', 'Bedok Int', 2, 7, true),
      generateArrivals('14', 'Bedok Int', 4, 9, true),
      generateArrivals('16', 'Bedok Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('36', 'Changi Airport PTB2', 6, 12, true),
      generateArrivals('77', 'Marina Ctr Ter', 3, 8, true),
      generateArrivals('106', 'Shenton Way Ter', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('111', 'Ghim Moh Ter', 5, 10, true),
      generateArrivals('131', 'Bukit Merah Int', 0, 5, true),
      generateArrivals('167', 'Bukit Merah Int', 7, 11, true),
      generateArrivals('171', 'Yishun Int', 9, 14, false, 'Only two arrivals scheduled'),
    ],
  },

  // 15. Stop 04179: Raffles Hotel
  {
    id: 'stop-04179',
    code: '04179',
    name: 'Raffles Hotel',
    road: 'Bras Basah Rd',
    postalCode: '189560',
    latitude: 1.2965,
    longitude: 103.8542,
    distanceMeters: 260,
    walkingTimeMins: 3,
    busServices: ['14', '16', '36', '77', '106', '111', '130', '131', '167'],
    buses: [
      generateArrivals('14', 'Clementi Int', 3, 8, true),
      generateArrivals('16', 'Bukit Merah Int', 5, 10, true),
      generateArrivals('36', 'Tomlinson Rd', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('77', 'Bukit Batok Int', 7, 12, true),
      generateArrivals('106', 'Bukit Batok Int', 2, 7, true),
      generateArrivals('111', 'Ghim Moh Ter', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('130', 'Shenton Way Ter', 4, 9, true),
      generateArrivals('131', 'Saint Michael\'s Ter', 0, 5, true),
      generateArrivals('167', 'Sembawang Int', 6, 11, true),
    ],
  },

  // 16. Stop 09047: Orchard Blvd Stn Exit 1
  {
    id: 'stop-09047',
    code: '09047',
    name: 'Orchard Blvd Stn Exit 1',
    road: 'Orchard Blvd',
    postalCode: '248648',
    latitude: 1.3021,
    longitude: 103.824,
    distanceMeters: 80,
    walkingTimeMins: 1,
    busServices: ['14', '65', '106', '111', '174'],
    buses: [
      generateArrivals('14', 'Clementi Int via Dover Rd', 2, 7, true),
      generateArrivals('65', 'HarbourFront Int via Lower Delta', 5, 10, true),
      generateArrivals('106', 'Bukit Batok Int via Holland Rd', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('111', 'Ghim Moh Ter', 6, 11, true),
      generateArrivals('174', 'Boon Lay Int via Bukit Timah', 4, 9, false, 'No more buses tonight (last bus in service)'),
    ],
  },

  // 17. Stop 09022: Orchard Stn / Tangs
  {
    id: 'stop-09022',
    code: '09022',
    name: 'Orchard Stn / Tangs',
    road: 'Orchard Rd',
    postalCode: '238864',
    latitude: 1.3045,
    longitude: 103.833,
    distanceMeters: 300,
    walkingTimeMins: 4,
    busServices: ['36', '77', '124', '143', '167', '174', '190', '518'],
    buses: [
      generateArrivals('36', 'Changi Airport PTB2', 3, 8, true),
      generateArrivals('77', 'Marina Ctr Ter', 5, 10, true),
      generateArrivals('124', 'Telok Blangah Ter', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('143', 'Jurong East Int', 7, 12, true),
      generateArrivals('167', 'Bukit Merah Int', 2, 7, true),
      generateArrivals('174', 'New Bridge Rd Ter', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('190', 'Kampong Bahru Ter', 4, 9, true),
      generateArrivals('518', 'Pasir Ris Int', 0, 5, true),
    ],
  },

  // 18. Stop 09169: Opp Ngee Ann City
  {
    id: 'stop-09169',
    code: '09169',
    name: 'Opp Ngee Ann City',
    road: 'Orchard Rd',
    postalCode: '238872',
    latitude: 1.3028,
    longitude: 103.8358,
    distanceMeters: 320,
    walkingTimeMins: 4,
    busServices: ['7', '14', '16', '65', '106', '111', '123', '175', '502'],
    buses: [
      generateArrivals('7', 'Bedok Int', 2, 7, true),
      generateArrivals('14', 'Bedok Int', 4, 9, true),
      generateArrivals('16', 'Bedok Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('65', 'Tampines Int', 6, 11, true),
      generateArrivals('106', 'Shenton Way Ter', 3, 8, true),
      generateArrivals('111', 'Ghim Moh Ter', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('123', 'HarbourFront Int', 5, 10, true),
      generateArrivals('175', 'Geylang Lor 1 Ter', 0, 5, true),
      generateArrivals('502', 'Soon Lee Bus Park', 7, 12, true),
    ],
  },

  // 19. Stop 09179: The Heeren
  {
    id: 'stop-09179',
    code: '09179',
    name: 'The Heeren',
    road: 'Orchard Rd',
    postalCode: '238855',
    latitude: 1.3022,
    longitude: 103.8372,
    distanceMeters: 340,
    walkingTimeMins: 5,
    busServices: ['7', '14', '16', '65', '106', '111', '123', '175', '502'],
    buses: [
      generateArrivals('7', 'Bedok Int', 3, 8, true),
      generateArrivals('14', 'Bedok Int', 5, 10, true),
      generateArrivals('16', 'Bedok Int', 2, 7, false, 'Only two arrivals scheduled'),
      generateArrivals('65', 'Tampines Int', 7, 12, true),
      generateArrivals('106', 'Shenton Way Ter', 1, 6, true),
      generateArrivals('111', 'Ghim Moh Ter', 9, 14, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('123', 'HarbourFront Int', 4, 9, true),
      generateArrivals('175', 'Geylang Lor 1 Ter', 8, 13, true),
      generateArrivals('502', 'Soon Lee Bus Park', 0, 5, true),
    ],
  },

  // 20. Stop 08069: Opp Somerset Stn
  {
    id: 'stop-08069',
    code: '08069',
    name: 'Opp Somerset Stn',
    road: 'Orchard Rd',
    postalCode: '238865',
    latitude: 1.3009,
    longitude: 103.8384,
    distanceMeters: 350,
    walkingTimeMins: 5,
    busServices: ['7', '14', '16', '36', '65', '77', '106', '111', '123', '174'],
    buses: [
      generateArrivals('7', 'Bedok Int', 2, 7, true),
      generateArrivals('14', 'Bedok Int', 4, 9, true),
      generateArrivals('16', 'Bedok Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('36', 'Changi Airport PTB2', 6, 11, true),
      generateArrivals('65', 'Tampines Int', 3, 8, true),
      generateArrivals('77', 'Marina Ctr Ter', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('106', 'Shenton Way Ter', 5, 10, true),
      generateArrivals('111', 'Ghim Moh Ter', 0, 5, true),
      generateArrivals('123', 'HarbourFront Int', 7, 12, true),
      generateArrivals('174', 'New Bridge Rd Ter', 9, 14, true),
    ],
  },

  // 21. Stop 08059: Dhoby Ghaut Stn Exit B
  {
    id: 'stop-08059',
    code: '08059',
    name: 'Dhoby Ghaut Stn Exit B',
    road: 'Penang Rd',
    postalCode: '238459',
    latitude: 1.2982,
    longitude: 103.8452,
    distanceMeters: 370,
    walkingTimeMins: 5,
    busServices: ['7', '14', '16', '36', '77', '106', '111', '124', '167', '174'],
    buses: [
      generateArrivals('7', 'Clementi Int', 3, 8, true),
      generateArrivals('14', 'Clementi Int', 5, 10, true),
      generateArrivals('16', 'Bukit Merah Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('36', 'Tomlinson Rd', 7, 12, true),
      generateArrivals('77', 'Bukit Batok Int', 2, 7, true),
      generateArrivals('106', 'Bukit Batok Int', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('111', 'Ghim Moh Ter', 4, 9, true),
      generateArrivals('124', 'Saint Michael\'s Ter', 0, 5, true),
      generateArrivals('167', 'Sembawang Int', 6, 11, true),
      generateArrivals('174', 'Boon Lay Int', 9, 14, true),
    ],
  },

  // 22. Stop 01112: Bugis Stn Exit A
  {
    id: 'stop-01112',
    code: '01112',
    name: 'Bugis Stn Exit A',
    road: 'Victoria St',
    postalCode: '188062',
    latitude: 1.3012,
    longitude: 103.8558,
    distanceMeters: 410,
    walkingTimeMins: 6,
    busServices: ['2', '12', '33', '130', '133', '960'],
    buses: [
      generateArrivals('2', 'Changi Village Ter', 2, 7, true),
      generateArrivals('12', 'Pasir Ris Int', 4, 9, true),
      generateArrivals('33', 'Bedok Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('130', 'Ang Mo Kio Int', 6, 11, true),
      generateArrivals('133', 'Ang Mo Kio Int', 3, 8, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('960', 'Woodlands Int', 0, 5, true),
    ],
  },

  // 23. Stop 01113: Bugis Stn Exit D
  {
    id: 'stop-01113',
    code: '01113',
    name: 'Bugis Stn Exit D',
    road: 'Rochor Rd',
    postalCode: '188485',
    latitude: 1.3008,
    longitude: 103.8548,
    distanceMeters: 430,
    walkingTimeMins: 6,
    busServices: ['48', '57', '170', '851', '960', '980'],
    buses: [
      generateArrivals('48', 'Upp East Coast Ter', 3, 8, true),
      generateArrivals('57', 'Bishan Int', 5, 10, true),
      generateArrivals('170', 'Queen St Ter', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('851', 'Yishun Int', 7, 12, true),
      generateArrivals('960', 'Marina Ctr Ter', 2, 7, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('980', 'Geylang Lor 1 Ter', 4, 9, true),
    ],
  },

  // 24. Stop 01119: Opp Bugis Stn Exit C
  {
    id: 'stop-01119',
    code: '01119',
    name: 'Opp Bugis Stn Exit C',
    road: 'Victoria St',
    postalCode: '188061',
    latitude: 1.3009,
    longitude: 103.8564,
    distanceMeters: 440,
    walkingTimeMins: 6,
    busServices: ['2', '12', '33', '130', '133', '960'],
    buses: [
      generateArrivals('2', 'Kampong Bahru Ter', 2, 7, true),
      generateArrivals('12', 'Kampong Bahru Ter', 4, 9, true),
      generateArrivals('33', 'Kent Ridge Ter', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('130', 'Shenton Way Ter', 6, 11, true),
      generateArrivals('133', 'Shenton Way Ter', 3, 8, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('960', 'Marina Ctr Ter', 0, 5, true),
    ],
  },

  // 25. Stop 01129: Fu Lu Shou Complex
  {
    id: 'stop-01129',
    code: '01129',
    name: 'Fu Lu Shou Complex',
    road: 'Rochor Rd',
    postalCode: '188425',
    latitude: 1.3015,
    longitude: 103.8542,
    distanceMeters: 450,
    walkingTimeMins: 6,
    busServices: ['48', '57', '170', '851', '960', '980'],
    buses: [
      generateArrivals('48', 'Buona Vista Ter', 3, 8, true),
      generateArrivals('57', 'Bukit Merah Int', 5, 10, true),
      generateArrivals('170', 'Larkin Ter (JB)', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('851', 'Bukit Merah Int', 7, 12, true),
      generateArrivals('960', 'Woodlands Int', 2, 7, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('980', 'Sembawang Int', 4, 9, true),
    ],
  },

  // 26. Stop 01059: Parkview Sq
  {
    id: 'stop-01059',
    code: '01059',
    name: 'Parkview Sq',
    road: 'North Bridge Rd',
    postalCode: '188778',
    latitude: 1.3001,
    longitude: 103.8576,
    distanceMeters: 470,
    walkingTimeMins: 7,
    busServices: ['7', '32', '51', '61', '63', '80', '145', '175', '197'],
    buses: [
      generateArrivals('7', 'Clementi Int', 2, 7, true),
      generateArrivals('32', 'Buona Vista Ter', 4, 9, true),
      generateArrivals('51', 'Jurong East Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('61', 'Bukit Batok Int', 6, 11, true),
      generateArrivals('63', 'Rumah Tinggi Ter', 3, 8, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('80', 'HarbourFront Int', 5, 10, true),
      generateArrivals('145', 'Buona Vista Ter', 0, 5, true),
      generateArrivals('175', 'Clementi Int', 7, 12, true),
      generateArrivals('197', 'Jurong East Int', 8, 13, true),
    ],
  },

  // 27. Stop 03059: The Sail
  {
    id: 'stop-03059',
    code: '03059',
    name: 'The Sail',
    road: 'Marina Blvd',
    postalCode: '018987',
    latitude: 1.2819,
    longitude: 103.8528,
    distanceMeters: 520,
    walkingTimeMins: 7,
    busServices: ['97', '106', '133', '400', '513'],
    buses: [
      generateArrivals('97', 'Jurong East Int', 3, 8, true),
      generateArrivals('106', 'Bukit Batok Int', 5, 10, true),
      generateArrivals('133', 'Ang Mo Kio Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('400', 'Shenton Way Ter', 7, 12, true),
      generateArrivals('513', 'Shenton Way Ter', 2, 7, false, 'No more buses tonight (last bus in service)'),
    ],
  },

  // 28. Stop 03509: Marina Bay Financial Ctr
  {
    id: 'stop-03509',
    code: '03509',
    name: 'Marina Bay Financial Ctr',
    road: 'Marina Blvd',
    postalCode: '018981',
    latitude: 1.2798,
    longitude: 103.8541,
    distanceMeters: 540,
    walkingTimeMins: 8,
    busServices: ['97', '106', '133', '400', '513'],
    buses: [
      generateArrivals('97', 'Marina Ctr Ter', 2, 7, true),
      generateArrivals('106', 'Shenton Way Ter', 4, 9, true),
      generateArrivals('133', 'Shenton Way Ter', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('400', 'Marina South Pier', 6, 11, true),
      generateArrivals('513', 'Tampines Ave 5', 3, 8, false, 'No more buses tonight (last bus in service)'),
    ],
  },

  // 29. Stop 03511: Bayfront Stn Exit B / MBS
  {
    id: 'stop-03511',
    code: '03511',
    name: 'Bayfront Stn Exit B / MBS',
    road: 'Bayfront Ave',
    postalCode: '018956',
    latitude: 1.2828,
    longitude: 103.8589,
    distanceMeters: 560,
    walkingTimeMins: 8,
    busServices: ['97', '106', '133', '502', '518'],
    buses: [
      generateArrivals('97', 'Jurong East Int', 3, 8, true),
      generateArrivals('106', 'Bukit Batok Int', 5, 10, true),
      generateArrivals('133', 'Ang Mo Kio Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('502', 'Pioneer Rd North', 7, 12, true),
      generateArrivals('518', 'Pasir Ris Int', 2, 7, false, 'No more buses tonight (last bus in service)'),
    ],
  },

  // 30. Stop 03519: Opp Bayfront Stn
  {
    id: 'stop-03519',
    code: '03519',
    name: 'Opp Bayfront Stn',
    road: 'Bayfront Ave',
    postalCode: '018957',
    latitude: 1.2831,
    longitude: 103.8592,
    distanceMeters: 570,
    walkingTimeMins: 8,
    busServices: ['97', '106', '133', '502', '518'],
    buses: [
      generateArrivals('97', 'Marina Ctr Ter', 2, 7, true),
      generateArrivals('106', 'Shenton Way Ter', 4, 9, true),
      generateArrivals('133', 'Shenton Way Ter', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('502', 'Marina Bay Sands', 6, 11, true),
      generateArrivals('518', 'Bayfront Ave', 3, 8, false, 'No more buses tonight (last bus in service)'),
    ],
  },

  // 31. Stop 05019: Chinatown Stn Exit E
  {
    id: 'stop-05019',
    code: '05019',
    name: 'Chinatown Stn Exit E',
    road: 'Eu Tong Sen St',
    postalCode: '059817',
    latitude: 1.2845,
    longitude: 103.8443,
    distanceMeters: 590,
    walkingTimeMins: 8,
    busServices: ['2', '12', '33', '54', '61', '143', '147', '190'],
    buses: [
      generateArrivals('2', 'Changi Village Ter', 3, 8, true),
      generateArrivals('12', 'Pasir Ris Int', 5, 10, true),
      generateArrivals('33', 'Bedok Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('54', 'Bishan Int', 7, 12, true),
      generateArrivals('61', 'Eunos Int', 2, 7, true),
      generateArrivals('143', 'Toa Payoh Int', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('147', 'Hougang Central Int', 4, 9, true),
      generateArrivals('190', 'Choa Chu Kang Int', 0, 5, true),
    ],
  },

  // 32. Stop 05429: Tanjong Pagar Stn Exit C
  {
    id: 'stop-05429',
    code: '05429',
    name: 'Tanjong Pagar Stn Exit C',
    road: 'Anson Rd',
    postalCode: '079906',
    latitude: 1.2764,
    longitude: 103.8465,
    distanceMeters: 620,
    walkingTimeMins: 9,
    busServices: ['10', '70', '75', '97', '100', '106', '107', '130', '131', '167', '196'],
    buses: [
      generateArrivals('10', 'Tampines Int', 2, 7, true),
      generateArrivals('70', 'Yio Chu Kang Ter', 4, 9, true),
      generateArrivals('75', 'Gali Batu Ter', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('97', 'Marina Ctr Ter', 6, 11, true),
      generateArrivals('100', 'Serangoon Int', 3, 8, true),
      generateArrivals('106', 'Shenton Way Ter', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('107', 'Hougang Central Int', 5, 10, true),
      generateArrivals('130', 'Ang Mo Kio Int', 0, 5, true),
      generateArrivals('131', 'Saint Michael\'s Ter', 7, 12, true),
      generateArrivals('167', 'Sembawang Int', 9, 14, false, 'Only two arrivals scheduled'),
      generateArrivals('196', 'Bedok Int', 1, 6, true),
    ],
  },

  // 33. Stop 11389: Buona Vista Stn Exit C
  {
    id: 'stop-11389',
    code: '11389',
    name: 'Buona Vista Stn Exit C',
    road: 'North Buona Vista Rd',
    postalCode: '138647',
    latitude: 1.3068,
    longitude: 103.7904,
    distanceMeters: 640,
    walkingTimeMins: 9,
    busServices: ['74', '91', '92', '95', '191', '196', '198', '200'],
    buses: [
      generateArrivals('74', 'Hougang Central Int', 3, 8, true),
      generateArrivals('91', 'Ayer Rajah Cres (Loop)', 5, 10, true),
      generateArrivals('92', 'Ghim Moh Ter', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('95', 'Kent Ridge Ter', 7, 12, true),
      generateArrivals('191', 'Buona Vista Ter', 2, 7, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('196', 'Bedok Int', 4, 9, true),
      generateArrivals('198', 'Jurong Town Hall Int', 0, 5, true),
      generateArrivals('200', 'Kent Ridge Ter', 8, 13, true),
    ],
  },

  // 34. Stop 17179: Clementi Stn Exit A
  {
    id: 'stop-17179',
    code: '17179',
    name: 'Clementi Stn Exit A',
    road: 'Commonwealth Ave West',
    postalCode: '120442',
    latitude: 1.3151,
    longitude: 103.7651,
    distanceMeters: 680,
    walkingTimeMins: 10,
    busServices: ['52', '96', '99', '147', '156', '165', '166', '175', '196', '285'],
    buses: [
      generateArrivals('52', 'Bishan Int', 2, 7, true),
      generateArrivals('96', 'Clementi Int', 4, 9, true),
      generateArrivals('99', 'Joo Koon Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('147', 'Hougang Central Int', 6, 11, true),
      generateArrivals('156', 'Sengkang Int', 3, 8, true),
      generateArrivals('165', 'Hougang Central Int', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('166', 'Ang Mo Kio Int', 5, 10, true),
      generateArrivals('175', 'Geylang Lor 1 Ter', 0, 5, true),
      generateArrivals('196', 'Bedok Int', 7, 12, true),
      generateArrivals('285', 'Clementi Int', 9, 14, false, 'Only two arrivals scheduled'),
    ],
  },

  // 35. Stop 28009: Jurong East Int
  {
    id: 'stop-28009',
    code: '28009',
    name: 'Jurong East Int',
    road: 'Jurong Gateway Rd',
    postalCode: '608544',
    latitude: 1.3331,
    longitude: 103.7423,
    distanceMeters: 710,
    walkingTimeMins: 10,
    busServices: ['41', '49', '51', '52', '66', '78', '79', '97', '98', '105', '143', '160', '197'],
    buses: [
      generateArrivals('41', 'Jalan Anak Bukit', 3, 8, true),
      generateArrivals('49', 'Taman Jurong', 5, 10, true),
      generateArrivals('51', 'Hougang Central Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('52', 'Bishan Int', 7, 12, true),
      generateArrivals('66', 'Bedok Int', 2, 7, true),
      generateArrivals('78', 'Clementi Ave 3', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('79', 'Boon Lay Int', 4, 9, true),
      generateArrivals('97', 'Marina Ctr Ter', 0, 5, true),
      generateArrivals('98', 'Jurong Island Checkpoint', 6, 11, true),
      generateArrivals('105', 'Serangoon Int', 9, 14, false, 'Only two arrivals scheduled'),
      generateArrivals('143', 'Toa Payoh Int', 2, 8, true),
      generateArrivals('160', 'JB Sentral Ter', 4, 9, true),
      generateArrivals('197', 'Bedok Int', 1, 6, true),
    ],
  },

  // 36. Stop 22009: Boon Lay Int
  {
    id: 'stop-22009',
    code: '22009',
    name: 'Boon Lay Int',
    road: 'Jurong West Ctrl 3',
    postalCode: '648346',
    latitude: 1.3392,
    longitude: 103.7056,
    distanceMeters: 750,
    walkingTimeMins: 11,
    busServices: ['30', '79', '154', '157', '172', '174', '178', '179', '180', '187', '198', '240'],
    buses: [
      generateArrivals('30', 'Bedok Int', 2, 7, true),
      generateArrivals('79', 'Jurong East Int', 4, 9, true),
      generateArrivals('154', 'Eunos Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('157', 'Toa Payoh Int', 6, 11, true),
      generateArrivals('172', 'Choa Chu Kang Int', 3, 8, true),
      generateArrivals('174', 'New Bridge Rd Ter', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('178', 'Woodlands Int', 5, 10, true),
      generateArrivals('179', 'NTU Hall 1', 0, 5, true),
      generateArrivals('180', 'Bukit Panjang Int', 7, 12, true),
      generateArrivals('187', 'Woodlands Int', 9, 14, false, 'Only two arrivals scheduled'),
      generateArrivals('198', 'Bukit Merah Int', 2, 7, true),
      generateArrivals('240', 'Kang Ching Rd', 4, 9, true),
    ],
  },

  // 37. Stop 44009: Choa Chu Kang Int
  {
    id: 'stop-44009',
    code: '44009',
    name: 'Choa Chu Kang Int',
    road: 'Choa Chu Kang Loop',
    postalCode: '689679',
    latitude: 1.3853,
    longitude: 103.7444,
    distanceMeters: 780,
    walkingTimeMins: 12,
    busServices: ['67', '172', '190', '300', '301', '302', '307', '925', '983', '985'],
    buses: [
      generateArrivals('67', 'Tampines Int', 3, 8, true),
      generateArrivals('172', 'Boon Lay Int', 5, 10, true),
      generateArrivals('190', 'Kampong Bahru Ter', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('300', 'CCK Ave 3 (Loop)', 7, 12, true),
      generateArrivals('301', 'CCK Ave 5 (Loop)', 2, 7, true),
      generateArrivals('302', 'Crescent (Loop)', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('307', 'CCK Ctrl (Loop)', 4, 9, true),
      generateArrivals('925', 'Woodlands Int', 0, 5, true),
      generateArrivals('983', 'Bukit Panjang', 6, 11, true),
      generateArrivals('985', 'Lor 1 Geylang Ter', 9, 14, false, 'Only two arrivals scheduled'),
    ],
  },

  // 38. Stop 45009: Bukit Panjang Int
  {
    id: 'stop-45009',
    code: '45009',
    name: 'Bukit Panjang Int',
    road: 'Jelebu Rd',
    postalCode: '677743',
    latitude: 1.3789,
    longitude: 103.7628,
    distanceMeters: 800,
    walkingTimeMins: 12,
    busServices: ['176', '180', '184', '920', '922', '970', '972', '973', '975', '976', '979'],
    buses: [
      generateArrivals('176', 'Bukit Merah Int', 2, 7, true),
      generateArrivals('180', 'Boon Lay Int', 4, 9, true),
      generateArrivals('184', 'Clementi Stn', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('920', 'Bangkit Rd (Loop)', 6, 11, true),
      generateArrivals('922', 'Fajar Rd (Loop)', 3, 8, true),
      generateArrivals('970', 'Shenton Way Ter', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('972', 'Dhoby Ghaut Stn', 5, 10, true),
      generateArrivals('973', 'Dairy Farm Rd', 0, 5, true),
      generateArrivals('975', 'Lim Chu Kang Rd', 7, 12, true),
      generateArrivals('976', 'Choa Chu Kang Int', 9, 14, false, 'Only two arrivals scheduled'),
      generateArrivals('979', 'Yew Tee Stn', 2, 8, true),
    ],
  },

  // 39. Stop 46009: Woodlands Int
  {
    id: 'stop-46009',
    code: '46009',
    name: 'Woodlands Int',
    road: 'Woodlands Sq',
    postalCode: '737736',
    latitude: 1.4369,
    longitude: 103.7865,
    distanceMeters: 830,
    walkingTimeMins: 13,
    busServices: ['161', '168', '169', '178', '187', '856', '900', '901', '903', '911', '960', '969'],
    buses: [
      generateArrivals('161', 'Hougang Central Int', 3, 8, true),
      generateArrivals('168', 'Bedok Int via Tampines', 5, 10, true),
      generateArrivals('169', 'Ang Mo Kio Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('178', 'Boon Lay Int', 7, 12, true),
      generateArrivals('187', 'Boon Lay Int', 2, 7, true),
      generateArrivals('856', 'Yishun Int', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('900', 'Woodlands Ave 4', 4, 9, true),
      generateArrivals('901', 'Woodlands Ave 6', 0, 5, true),
      generateArrivals('903', 'Woodlands Ctr Rd', 6, 11, true),
      generateArrivals('911', 'Woodlands Ave 2', 9, 14, false, 'Only two arrivals scheduled'),
      generateArrivals('960', 'Marina Ctr Ter', 2, 7, true),
      generateArrivals('969', 'Tampines Int via SLE', 4, 9, true),
    ],
  },

  // 40. Stop 53009: Bishan Int
  {
    id: 'stop-53009',
    code: '53009',
    name: 'Bishan Int',
    road: 'Bishan St 13',
    postalCode: '579796',
    latitude: 1.3508,
    longitude: 103.8488,
    distanceMeters: 850,
    walkingTimeMins: 13,
    busServices: ['50', '52', '53', '54', '55', '56', '57', '58', '59', '410G', '410W'],
    buses: [
      generateArrivals('50', 'Punggol Temp Int', 2, 7, true),
      generateArrivals('52', 'Jurong East Int', 4, 9, true),
      generateArrivals('53', 'Changi Airport PTB2', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('54', 'New Bridge Rd Ter', 6, 11, true),
      generateArrivals('55', 'Siglap Rd', 3, 8, true),
      generateArrivals('56', 'Marina Ctr Ter', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('57', 'Bukit Merah Int', 5, 10, true),
      generateArrivals('58', 'Pasir Ris Int', 0, 5, true),
      generateArrivals('59', 'Changi Village Ter', 7, 12, true),
      generateArrivals('410G', 'Shunfu Rd', 9, 14, false, 'Only two arrivals scheduled'),
      generateArrivals('410W', 'Marymount Rd', 2, 8, true),
    ],
  },

  // 41. Stop 54009: Ang Mo Kio Int
  {
    id: 'stop-54009',
    code: '54009',
    name: 'Ang Mo Kio Int',
    road: 'Ang Mo Kio Ave 8',
    postalCode: '569814',
    latitude: 1.3698,
    longitude: 103.8496,
    distanceMeters: 880,
    walkingTimeMins: 14,
    busServices: ['22', '24', '25', '73', '86', '130', '133', '135', '136', '138', '166', '169'],
    buses: [
      generateArrivals('22', 'Tampines Int', 3, 8, true),
      generateArrivals('24', 'Changi Airport PTB2', 5, 10, true),
      generateArrivals('25', 'Bedok Int', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('73', 'Toa Payoh Int', 7, 12, true),
      generateArrivals('86', 'Sengkang Int', 2, 7, true),
      generateArrivals('130', 'Shenton Way Ter', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('133', 'Shenton Way Ter', 4, 9, true),
      generateArrivals('135', 'Siglap Rd', 0, 5, true),
      generateArrivals('136', 'Punggol Temp Int', 6, 11, true),
      generateArrivals('138', 'Singapore Zoo', 9, 14, false, 'Only two arrivals scheduled'),
      generateArrivals('166', 'Clementi Int', 2, 8, true),
      generateArrivals('169', 'Woodlands Int', 4, 9, true),
    ],
  },

  // 42. Stop 75009: Tampines Int
  {
    id: 'stop-75009',
    code: '75009',
    name: 'Tampines Int',
    road: 'Tampines Ctrl 1',
    postalCode: '529538',
    latitude: 1.3533,
    longitude: 103.9452,
    distanceMeters: 920,
    walkingTimeMins: 14,
    busServices: ['4', '8', '10', '19', '20', '23', '28', '29', '31', '38', '65', '67', '72'],
    buses: [
      generateArrivals('4', 'Changi Prison', 2, 7, true),
      generateArrivals('8', 'Toa Payoh Int', 4, 9, true),
      generateArrivals('10', 'Kent Ridge Ter', 1, 6, false, 'Only two arrivals scheduled'),
      generateArrivals('19', 'Changi Cargo Ter', 6, 11, true),
      generateArrivals('20', 'Changi Business Pk', 3, 8, true),
      generateArrivals('23', 'Rochor Stn', 8, 13, false, 'No more buses tonight (last bus in service)'),
      generateArrivals('28', 'Toa Payoh Int', 5, 10, true),
      generateArrivals('29', 'Changi Village Ter', 0, 5, true),
      generateArrivals('31', 'Toa Payoh Int', 7, 12, true),
      generateArrivals('38', 'Bedok Int', 9, 14, false, 'Only two arrivals scheduled'),
      generateArrivals('65', 'HarbourFront Int', 2, 8, true),
      generateArrivals('67', 'Choa Chu Kang Int', 4, 9, true),
      generateArrivals('72', 'Yio Chu Kang Ter', 1, 6, true),
    ],
  },
];

/** Fast O(1) map for all bus stops by 5-digit code */
export const BUS_STOPS_MAP: Record<string, BusStop> = {};
for (const stop of BUS_STOPS_DATA) {
  BUS_STOPS_MAP[stop.code] = stop;
}

/** Locations presets to calculate nearest bus stops */
export interface MeasuringLocation {
  id: string;
  name: string;
  label: string;
  latitude: number;
  longitude: number;
}

export const MEASURING_LOCATIONS: MeasuringLocation[] = [
  {
    id: 'orchard',
    name: 'Orchard Road (Central Area)',
    label: 'Orchard Road (Central Area)',
    latitude: 1.3023,
    longitude: 103.8242,
  },
  {
    id: 'cityhall',
    name: 'City Hall / Civic District',
    label: 'City Hall / Civic District',
    latitude: 1.2931,
    longitude: 103.8519,
  },
  {
    id: 'thomson',
    name: 'Upper Thomson / Thomson Plaza',
    label: 'Upper Thomson / Thomson Plaza',
    latitude: 1.3547,
    longitude: 103.8315,
  },
  {
    id: 'bugis',
    name: 'Bugis / Victoria Street',
    label: 'Bugis / Victoria Street',
    latitude: 1.3005,
    longitude: 103.856,
  },
  {
    id: 'harbourfront',
    name: 'HarbourFront / Telok Blangah',
    label: 'HarbourFront / Telok Blangah',
    latitude: 1.2644,
    longitude: 103.8222,
  },
  {
    id: 'jurong',
    name: 'Jurong East Central',
    label: 'Jurong East Central',
    latitude: 1.3331,
    longitude: 103.7423,
  },
  {
    id: 'woodlands',
    name: 'Woodlands Square',
    label: 'Woodlands Square',
    latitude: 1.4369,
    longitude: 103.7865,
  },
  {
    id: 'tampines',
    name: 'Tampines Central',
    label: 'Tampines Central',
    latitude: 1.3533,
    longitude: 103.9452,
  },
];

/** Geodesic distance calculation in meters using the Haversine formula */
export function getDistanceInMeters(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371000;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c);
}
